#!/usr/bin/env python3
"""Build the warzone using CCP's exact in-game 2D layout and ESI gates."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
data = json.loads((ROOT / 'research/warzone.json').read_text())
layout = json.loads((ROOT / 'research/map-layout.json').read_text())
positions = {s['id']: s['position2D'] for s in layout['systems']}
original = {s['solar_system_id']: s['owner_faction_id'] for s in data['roster']}
raw = sorted(data['systems'], key=lambda s: s['name'])
index = {s['system_id']: i for i, s in enumerate(raw)}
constellations = sorted(data['constellations'].values(), key=lambda c: c['name'])
group_index = {c['constellation_id']: i for i, c in enumerate(constellations)}
edges = [[index[a], index[b]] for a, b in data['edges']]
neighbors = [[] for _ in raw]
for a, b in edges:
    neighbors[a].append(b)
    neighbors[b].append(a)

# A common scale and the standard north-positive to screen-down Y conversion
# preserve the actual EVE client's 2D map, including every relative distance.
width, height, padding = 1710, 1290, 90
min_x, max_x = min(p['x'] for p in positions.values()), max(p['x'] for p in positions.values())
min_y, max_y = min(p['y'] for p in positions.values()), max(p['y'] for p in positions.values())
scale = min((width - 2 * padding) / (max_x - min_x), (height - 2 * padding) / (max_y - min_y))
offset_x = (width - (max_x - min_x) * scale) / 2
offset_y = (height - (max_y - min_y) * scale) / 2
groups = []
for c in constellations:
    members = [i for i, s in enumerate(raw) if s['constellation_id'] == c['constellation_id']]
    frontier = sum(any(j not in members for j in neighbors[i]) for i in members)
    groups.append({'name': c['name'], 'region': data['regions'][str(c['region_id'])]['name'],
                   'systems': members, 'bonus': max(1, round((len(members) + frontier) / 3))})
systems = []
for s in raw:
    p = positions[s['system_id']]
    systems.append({'id': s['system_id'], 'name': s['name'],
                    'group': group_index[s['constellation_id']], 'security': round(s['security_status'], 1),
                    'faction': 'caldari' if original[s['system_id']] == 500001 else 'gallente',
                    'x': round(offset_x + (p['x'] - min_x) * scale, 6),
                    'y': round(offset_y + (max_y - p['y']) * scale, 6)})
metadata = {'layout': 'CCP in-game 2D', 'build': layout['build'], 'width': width, 'height': height,
            'scale': scale, 'offsetX': offset_x, 'offsetY': offset_y,
            'minX': min_x, 'maxY': max_y, 'source': layout['source']}
content = '// Generated by scripts/build-map.py from frozen CCP SDE positions and public ESI gates.\n'
for name, value in [('SYSTEMS', systems), ('GROUPS', groups), ('EDGES', edges), ('NEIGHBORS', neighbors), ('MAP_LAYOUT', metadata)]:
    content += f'export const {name} = ' + json.dumps(value, separators=(',', ':')) + ';\n'
(ROOT / 'map-data.js').write_text(content)
print(f"Built {len(systems)} systems and {len(edges)} gates using CCP's in-game 2D positions.")
